    const exercisesData = {
        'Verb to be': [
            // Nivel Básico (1-30)
            { q: "She ___ a doctor.", a: "is", alt: "'s" },
            { q: "I ___ from Mexico.", a: "'m", alt: "am" },
            { q: "They are not here. -> They ___ here.", a: "aren't", alt: "are not" },
            { q: "___ you happy?", a: "Are" },
            { q: "He is a good student. -> ___ a good student.", a: "He's", alt: "He is" },
            { q: "We are friends. -> ___ friends.", a: "We're", alt: "We are" },
            { q: "It is cold today. -> ___ cold today.", a: "It's", alt: "It is" },
            { q: "My name ___ Carlos.", a: "is" },
            { q: "You are a pilot. -> ___ a pilot.", a: "You're", alt: "You are" },
            { q: "His parents ___ on vacation.", a: "are" },
            { q: "The book ___ on the table.", a: "is" },
            { q: "I am not tired. -> I ___ tired.", a: "'m not", alt: "am not" },
            { q: "___ she your sister?", a: "Is" },
            { q: "The cats ___ sleeping.", a: "are" },
            { q: "What ___ your name?", a: "is", alt: "'s" },
            { q: "How old ___ you?", a: "are" },
            { q: "This ___ my house.", a: "is" },
            { q: "We ___ ready to go.", a: "'re", alt: "are" },
            { q: "___ I late?", a: "Am" },
            { q: "He is not an engineer. -> He ___ an engineer.", a: "isn't", alt: "is not" },
            { q: "They ___ students.", a: "are", alt: "'re" },
            { q: "My sister ___ young.", a: "is", alt: "'s" },
            { q: "The dogs ___ outside.", a: "are" },
            { q: "___ it a good movie?", a: "Is" },
            { q: "I ___ not sad.", a: "'m not", alt: "am not" },
            { q: "You are not busy. -> You ___ busy.", a: "aren't", alt: "are not" },
            { q: "Where ___ you from?", a: "are" },
            { q: "This apple ___ red.", a: "is" },
            { q: "These chairs ___ old.", a: "are" },
            { q: "She ___ my friend.", a: "is", alt: "'s" },
            // Nivel Intermedio (31-50)
            { q: "I ___ a student.", a: "'m", alt: "am" },
            { q: "You ___ my best friend.", a: "'re", alt: "are" },
            { q: "It ___ a beautiful day.", a: "'s", alt: "is" },
            { q: "She ___ from Spain.", a: "isn't", alt: "is not" },
            { q: "We ___ in the same class.", a: "'re", alt: "are" },
            { q: "They ___ brothers.", a: "are" },
            { q: "My brother ___ tall.", a: "is", alt: "'s" },
            { q: "The dogs ___ in the garden.", a: "are" },
            { q: "___ he your teacher?", a: "Is" },
            { q: "That ___ not my problem. -> That ___ my problem.", a: "isn't", alt: "is not" },
            { q: "Where ___ my keys?", a: "are" },
            { q: "The news ___ very interesting today.", a: "is" },
            { q: "Your shoes ___ under the bed.", a: "are" },
            { q: "Maths ___ my favorite subject.", a: "is" },
            { q: "How ___ your parents?", a: "are" },
            { q: "There ___ a lot of people here.", a: "are" },
            { q: "Our teacher ___ very kind.", a: "is" },
            { q: "I think you ___ wrong.", a: "'re", alt: "are" },
            { q: "The children ___ hungry.", a: "are" },
            { q: "The weather ___ nice today, isn't it?", a: "is" },
            // Nivel Avanzado (51-60)
            { q: "Neither my brother nor I ___ going to the party.", a: "am" },
            { q: "The police ___ investigating the case.", a: "are" },
            { q: "The scissors ___ on the desk.", a: "are" },
            { q: "A lot of the information ___ incorrect.", a: "is" },
            { q: "All of the students ___ present.", a: "are" },
            { q: "Fifty dollars ___ too much to pay.", a: "is" },
            { q: "The committee ___ in agreement.", a: "is" },
            { q: "A pair of trousers ___ in the washing machine.", a: "is" },
            { q: "Each of the members ___ a vote.", a: "has" },
            { q: "The United States ___ a large country.", a: "is" }
        ],
        'Present Continuous': [
            // Nivel Básico (1-30)
            { q: "He (read)___ a book.", a: "is reading", alt: "'s reading" },
            { q: "They (play)___ football.", a: "are playing", alt: "'re playing" },
            { q: "I (do)___ my homework.", a: "am doing", alt: "'m doing" },
            { q: "She (watch)___ TV.", a: "is watching", alt: "'s watching" },
            { q: "We (listen)___ to music.", a: "are listening", alt: "'re listening" },
            { q: "The sun (shine)___.", a: "is shining", alt: "'s shining" },
            { q: "Why ___ you (cry)___?", a: "are / crying" },
            { q: "He (not sleep)___.", a: "isn't sleeping", alt: "is not sleeping" },
            { q: "I (write)___ an email.", a: "am writing", alt: "'m writing" },
            { q: "They (have)___ dinner.", a: "are having", alt: "'re having" },
            { q: "___ you (go)___ to the party?", a: "Are / going" },
            { q: "The dog (run)___ in the park.", a: "is running", alt: "'s running" },
            { q: "She (talk)___ on the phone.", a: "is talking", alt: "'s talking" },
            { q: "We (study)___ for the exam.", a: "are studying", alt: "'re studying" },
            { q: "It (rain)___ outside.", a: "is raining", alt: "'s raining" },
            { q: "I (sit)___ on the sofa.", a: "am sitting", alt: "'m sitting" },
            { q: "What ___ they (eat)___?", a: "are / eating" },
            { q: "He (drive)___ his new car.", a: "is driving", alt: "'s driving" },
            { q: "You (make)___ a lot of noise.", a: "are making", alt: "'re making" },
            { q: "She (wear)___ a beautiful dress.", a: "is wearing", alt: "'s wearing" },
            { q: "The cat (sleep)___ on the chair.", a: "is sleeping", alt: "'s sleeping" },
            { q: "I (eat)___ breakfast now.", a: "am eating", alt: "'m eating" },
            { q: "You (listen)___ to me?", a: "Are you listening" },
            { q: "They (walk)___ to school.", a: "are walking", alt: "'re walking" },
            { q: "She (sing)___ a song.", a: "is singing", alt: "'s singing" },
            { q: "We (not play)___ a game right now.", a: "aren't playing", alt: "are not playing" },
            { q: "The baby (laugh)___.", a: "is laughing", alt: "'s laughing" },
            { q: "What ___ you (read)___?", a: "are / reading" },
            { q: "He (swim)___ in the pool.", a: "is swimming", alt: "'s swimming" },
            { q: "It (not work)___. I need to fix it.", a: "isn't working", alt: "is not working" },
            // Nivel Intermedio (31-50)
            { q: "The chefs (cook)___ in the kitchen.", a: "are cooking" },
            { q: "My sister (learn)___ French.", a: "is learning", alt: "'s learning" },
            { q: "I (not work)___ today.", a: "'m not working", alt: "am not working" },
            { q: "What song ___ you (sing)___?", a: "are / singing" },
            { q: "The kids (build)___ a sandcastle.", a: "are building", alt: "'re building" },
            { q: "He (wait)___ for the bus.", a: "is waiting", alt: "'s waiting" },
            { q: "Look! It (snow)___!", a: "is snowing", alt: "'s snowing" },
            { q: "We (plan)___ our vacation.", a: "are planning", alt: "'re planning" },
            { q: "She (not feel)___ well.", a: "isn't feeling", alt: "is not feeling" },
            { q: "The phone (ring)___.", a: "is ringing", alt: "'s ringing" },
            { q: "My friends (travel)___ to Japan this month.", a: "are traveling" },
            { q: "Be quiet! The baby (sleep)___.", a: "is sleeping" },
            { q: "He always (complain)___ about everything.", a: "is complaining" },
            { q: "The company (grow)___ quickly.", a: "is growing" },
            { q: "She (get)___ better at playing the piano.", a: "is getting" },
            { q: "Why ___ you always (interrupt)___ me?", a: "are / interrupting" },
            { q: "He (stand)___ on my foot!", a: "is standing" },
            { q: "The world (change)___ rapidly.", a: "is changing" },
            { q: "I (think)___ about my future.", a: "am thinking" },
            { q: "They (build)___ a new bridge in the city.", a: "are building" },
            // Nivel Avanzado (51-60)
            { q: "This week, I (read)___ a very interesting book.", a: "am reading" },
            { q: "The population of the city (increase)___ every year.", a: "is increasing" },
            { q: "She (consider)___ moving to another country.", a: "is considering" },
            { q: "He (temporarily work)___ as a waiter.", a: "is temporarily working" },
            { q: "My English (improve)___.", a: "is improving" },
            { q: "You (constantly lose)___ your keys!", a: "are constantly losing" },
            { q: "The climate (become)___ warmer.", a: "is becoming" },
            { q: "We (look forward)___ to our holiday.", a: "are looking forward" },
            { q: "The two companies (negotiate)___ a merger.", a: "are negotiating" },
            { q: "What ___ you (do)___ this evening?", a: "are / doing" }
        ],
        'Possessive Adjectives': [
             // Nivel Básico (1-30)
            { q: "This is ___ book. (I)", a: "my" },
            { q: "She forgot ___ keys. (She)", a: "her" },
            { q: "He is washing ___ car. (He)", a: "his" },
            { q: "That is ___ house. (They)", a: "their" },
            { q: "The cat is eating ___ food. (It)", a: "its" },
            { q: "We love ___ new teacher. (We)", a: "our" },
            { q: "What is ___ name? (You)", a: "your" },
            { q: "I need to find ___ phone.", a: "my" },
            { q: "Is this ___ bag? (you)", a: "your" },
            { q: "They are visiting ___ grandparents.", a: "their" },
            { q: "Maria is with ___ friends.", a: "her" },
            { q: "Juan is playing with ___ brother.", a: "his" },
            { q: "The company increased ___ profits.", a: "its" },
            { q: "We sold ___ old computer.", a: "our" },
            { q: "Is that ___ dog? (he)", a: "his" },
            { q: "I like ___ new shoes. (she)", a: "her" },
            { q: "The students are doing ___ homework.", a: "their" },
            { q: "Can I borrow ___ pen? (you)", a: "your" },
            { q: "We painted ___ bedroom blue.", a: "our" },
            { q: "The bird is in ___ cage.", a: "its" },
            { q: "This is ___ father. (I)", a: "my" },
            { q: "Where is ___ mother? (You)", a: "your" },
            { q: "He loves ___ family. (He)", a: "his" },
            { q: "She is calling ___ sister. (She)", a: "her" },
            { q: "We need ___ tickets. (We)", a: "our" },
            { q: "They forgot ___ coats. (They)", a: "their" },
            { q: "The dog is wagging ___ tail. (It)", a: "its" },
            { q: "___ name is Ana. (She)", a: "Her" },
            { q: "___ name is Tom. (He)", a: "His" },
            { q: "What are ___ hobbies? (You)", a: "your" },
            // Nivel Intermedio (31-50)
            { q: "Hi, I'm a doctor. ___ name is Phil.", a: "My" },
            { q: "They're actors. ___ favorite film is Star Wars.", a: "Their" },
            { q: "He's French but ___ wife is English.", a: "his" },
            { q: "We're Russian. ___ names are Olga and Natalia.", a: "Our" },
            { q: "She's a waitress. ___ favorite food is pasta.", a: "Her" },
            { q: "It's my cat. ___ favorite drink is tea.", a: "Its" },
            { q: "What's ___ email address?", a: "your" },
            { q: "The children miss ___ parents.", a: "their" },
            { q: "He has a new bike. ___ bike is red.", a: "His" },
            { q: "She is a model. ___ job is interesting.", a: "Her" },
            { q: "Look at that tree! ___ leaves are beautiful.", a: "Its" },
            { q: "Could you tell me ___ phone number?", a: "your" },
            { q: "The team celebrated ___ victory.", a: "its" },
            { q: "I have a brother. ___ name is David.", a: "His" },
            { q: "My sister has a dog. ___ dog is very friendly.", a: "Her" },
            { q: "We are a family and this is ___ home.", a: "our" },
            { q: "The tourists are looking for ___ hotel.", a: "their" },
            { q: "John, you should clean ___ room.", a: "your" },
            { q: "I have to finish ___ project by tomorrow.", a: "my" },
            { q: "She showed me ___ new paintings.", a: "her" },
             // Nivel Avanzado (51-60)
            { q: "A country should protect ___ citizens.", a: "its" },
            { q: "Every student must bring ___ own book.", a: "his or her", alt: "their" },
            { q: "One must do ___ duty.", a: "one's" },
            { q: "The jury gave ___ verdict.", a: "its" },
            { q: "Each of the girls has ___ own room.", a: "her" },
            { q: "Neither of the boys has done ___ homework.", a: "his" },
            { q: "The robot moved ___ arm.", a: "its" },
            { q: "The audience showed ___ appreciation with applause.", a: "its", alt: "their" },
            { q: "Someone left ___ umbrella here.", a: "their" },
            { q: "The company is proud of ___ employees.", a: "its" }
        ],
        "Possessive 's' (Saxon)": [
            // Nivel Básico (1-30)
            { q: "This is the car of my father. -> This is ___ car.", a: "my father's" },
            { q: "The room of the children. -> The ___ room.", a: "children's" },
            { q: "The book of Maria. -> ___ book.", a: "Maria's" },
            { q: "The house of my friends. -> My ___ house.", a: "friends'" },
            { q: "The tail of the cat. -> The ___ tail.", a: "cat's" },
            { q: "The job of my brother. -> My ___ job.", a: "brother's" },
            { q: "The capital of France. -> ___ capital is Paris.", a: "France's" },
            { q: "The toys of the dog. -> The ___ toys.", a: "dog's" },
            { q: "The computer of James. -> ___ computer.", a: "James's", alt: "James'" },
            { q: "The school of my sisters. -> My ___ school.", a: "sisters'" },
            { q: "The ideas of the boss. -> The ___ ideas.", a: "boss's" },
            { q: "The team of the players. -> The ___ team.", a: "players'" },
            { q: "The phone of my mother. -> My ___ phone.", a: "mother's" },
            { q: "The name of the girl. -> The ___ name.", a: "girl's" },
            { q: "The wife of Charles. -> ___ wife is a doctor.", a: "Charles's", alt: "Charles'" },
            { q: "The decision of the government. -> The ___ decision.", a: "government's" },
            { q: "The uniform of the students. -> The ___ uniform.", a: "students'" },
            { q: "The new movie of the director. -> The ___ new movie.", a: "director's" },
            { q: "The end of the story. -> The ___ end.", a: "story's" },
            { q: "The opinion of the people. -> The ___ opinion.", a: "people's" },
            { q: "The bedroom of my sister. -> My ___ bedroom.", a: "sister's" },
            { q: "The car of my parents. -> My ___ car.", a: "parents'" },
            { q: "The name of the man is Peter. -> The ___ name is Peter.", a: "man's" },
            { q: "The bone of the dog. -> The ___ bone.", a: "dog's" },
            { q: "The office of the boss. -> The ___ office.", a: "boss's" },
            { q: "The songs of the singer. -> The ___ songs.", a: "singer's" },
            { q: "The bikes of the boys. -> The ___ bikes.", a: "boys'" },
            { q: "The work of my uncle. -> My ___ work.", a: "uncle's" },
            { q: "The party of my friend. -> My ___ party.", a: "friend's" },
            { q: "The books of the women. -> The ___ books.", a: "women's" },
            // Nivel Intermedio (31-50)
            { q: "That is the dog of Joe. -> That is ___ dog.", a: "Joe's" },
            { q: "This is the cousin of my mother. -> This is my ___ cousin.", a: "mother's" },
            { q: "The name of my father is Tom. -> My ___ name is Tom.", a: "father's" },
            { q: "The sister of my brothers is Sandy. -> My ___ sister is Sandy.", a: "brothers'" },
            { q: "The friend of my best friend is Tim. -> My ___ friend is Tim.", a: "best friend's" },
            { q: "The bikes of the boys are new. -> The ___ bikes are new.", a: "boys'" },
            { q: "The car of Mr. Smith is expensive. -> ___ car is expensive.", a: "Mr. Smith's" },
            { q: "The presentation of the student was great. -> The ___ presentation was great.", a: "student's" },
            { q: "The office of my parents is downtown. -> My ___ office is downtown.", a: "parents'" },
            { q: "The poems of the writer are famous. -> The ___ poems are famous.", a: "writer's" },
            { q: "The laptop of my sister is new. -> My ___ laptop is new.", a: "sister's" },
            { q: "The classroom of the teachers is big. -> The ___ classroom is big.", a: "teachers'" },
            { q: "The color of the car is red. -> The ___ color is red.", a: "car's" },
            { q: "The wedding of my cousin is next week. -> My ___ wedding is next week.", a: "cousin's" },
            { q: "The claws of the cat are sharp. -> The ___ claws are sharp.", a: "cat's" },
            { q: "The husband of my aunt is my uncle. -> My ___ husband is my uncle.", a: "aunt's" },
            { q: "The performance of the actors was amazing. -> The ___ performance was amazing.", a: "actors'" },
            { q: "The house of Mr. and Mrs. Jones is beautiful. -> ___ house is beautiful.", a: "Mr. and Mrs. Jones's" },
            { q: "The toys of the children are on the floor. -> The ___ toys are on the floor.", a: "children's" },
            { q: "The glasses of my grandma are on the table. -> My ___ glasses are on the table.", a: "grandma's" },
            // Nivel Avanzado (51-60)
            { q: "The economy of the country is growing. -> The ___ economy is growing.", a: "country's" },
            { q: "The history of the world is fascinating. -> The ___ history is fascinating.", a: "world's" },
            { q: "For the sake of goodness. -> For ___ sake.", a: "goodness'" },
            { q: "A journey of a week. -> A ___ journey.", a: "week's" },
            { q: "The plays of Shakespeare are famous. -> ___ plays are famous.", a: "Shakespeare's" },
            { q: "The speech of the president was long. -> The ___ speech was long.", a: "president's" },
            { q: "The policies of the two countries are different. -> The ___ policies are different.", a: "two countries'" },
            { q: "The novels of Dickens are still popular. -> ___ novels are still popular.", a: "Dickens's", alt: "Dickens'" },
            { q: "The rights of women are important. -> ___ rights are important.", a: "Women's" },
            { q: "The success of the project depends on teamwork. -> The ___ success depends on teamwork.", a: "project's" }
        ],
        'Family': [
            // Nivel Básico (1-30)
            { q: "Your mother's sister is your ___.", a: "aunt" },
            { q: "Your father's brother is your ___.", a: "uncle" },
            { q: "Your aunt's children are your ___.", a: "cousins" },
            { q: "Your sister's husband is your ___.", a: "brother-in-law" },
            { q: "Your mother's father is your ___.", a: "grandfather" },
            { q: "Your son's son is your ___.", a: "grandson" },
            { q: "Your brother's daughter is your ___.", a: "niece" },
            { q: "Your sister's son is your ___.", a: "nephew" },
            { q: "Your father's mother is your ___.", a: "grandmother" },
            { q: "Your father and mother are your ___.", a: "parents" },
            { q: "A boy with the same parents as you is your ___.", a: "brother" },
            { q: "A girl with the same parents as you is your ___.", a: "sister" },
            { q: "Your husband's mother is your ___.", a: "mother-in-law" },
            { q: "Your daughter's daughter is your ___.", a: "granddaughter" },
            { q: "Your father's new wife is your ___.", a: "stepmother" },
            { q: "Your wife's brother is your ___.", a: "brother-in-law" },
            { q: "The person you are married to (male) is your ___.", a: "husband" },
            { q: "The person you are married to (female) is your ___.", a: "wife" },
            { q: "A male child is a ___.", a: "son" },
            { q: "A female child is a ___.", a: "daughter" },
            { q: "Your mother's brother's wife is your ___.", a: "aunt" },
            { q: "Your father's sister's husband is your ___.", a: "uncle" },
            { q: "Your son and daughter are your ___.", a: "children" },
            { q: "Your grandmothers and grandfathers are your ___.", a: "grandparents" },
            { q: "The mother of your mother is your ___.", a: "grandmother" },
            { q: "The father of your father is your ___.", a: "grandfather" },
            { q: "A child who has no siblings is an ___ child.", a: "only" },
            { q: "Your wife's father is your ___.", a: "father-in-law" },
            { q: "Your husband's sister is your ___.", a: "sister-in-law" },
            { q: "A family get-together is a family ___.", a: "reunion" },
            // Nivel Intermedio (31-50)
            { q: "Your brother and sister are your ___.", a: "siblings" },
            { q: "Your mother and father's parents are your ___.", a: "grandparents" },
            { q: "Your father's sister is your ___.", a: "aunt" },
            { q: "Your uncle's son is your ___.", a: "cousin" },
            { q: "Your husband's father is your ___.", a: "father-in-law" },
            { q: "Your parents, siblings, aunts, etc., are your ___.", a: "relatives" },
            { q: "A child without brothers or sisters is an ___ child.", a: "only" },
            { q: "Your wife's sister is your ___.", a: "sister-in-law" },
            { q: "A man on his wedding day is the ___.", a: "groom" },
            { q: "A woman on her wedding day is the ___.", a: "bride" },
            { q: "Your mother's mother is your maternal ___.", a: "grandmother" },
            { q: "Your father's father is your paternal ___.", a: "grandfather" },
            { q: "Your wife's parents are your ___.", a: "parents-in-law" },
            { q: "Your son's wife is your ___.", a: "daughter-in-law" },
            { q: "Your daughter's husband is your ___.", a: "son-in-law" },
            { q: "A person who is not married is ___.", a: "single" },
            { q: "A woman whose husband has died is a ___.", a: "widow" },
            { q: "A man whose wife has died is a ___.", a: "widower" },
            { q: "Your father's brother's son is your ___.", a: "cousin" },
            { q: "Two babies born at the same time are ___.", a: "twins" },
            // Nivel Avanzado (51-60)
            { q: "Your mother's grandmother is your ___.", a: "great-grandmother" },
            { q: "Your grandfather's father is your ___.", a: "great-grandfather" },
            { q: "Your parents' parents' parents are your ___.", a: "great-grandparents" },
            { q: "A family with a mother, father, and children is a ___ family.", a: "nuclear" },
            { q: "A family including grandparents, aunts, uncles, etc., is an ___ family.", a: "extended" },
            { q: "The brother of your husband or wife is your ___.", a: "brother-in-law" },
            { q: "The child of your uncle or aunt is your ___.", a: "first cousin" },
            { q: "A child your parents adopt is your ___ sibling.", a: "adopted" },
            { q: "Your parents and their ancestors are your ___.", a: "forefathers", alt: "ancestors" },
            { q: "All the people in a family over generations are ___.", a: "descendants" }
        ],
        'Jobs & Occupations': [
             // Nivel Básico (1-30)
            { q: "Someone who flies a plane is a ___.", a: "pilot" },
            { q: "Someone who helps sick people in a hospital is a ___.", a: "doctor" },
            { q: "Someone who cuts hair is a ___.", a: "hairdresser" },
            { q: "Someone who teaches students is a ___.", a: "teacher" },
            { q: "Someone who cooks food in a restaurant is a ___.", a: "chef" },
            { q: "Someone who drives a taxi is a ___.", a: "taxi driver" },
            { q: "Someone who builds houses is a ___.", a: "builder" },
            { q: "Someone who sings songs is a ___.", a: "singer" },
            { q: "Someone who fixes cars is a ___.", a: "mechanic" },
            { q: "Someone who helps doctors in a hospital is a ___.", a: "nurse" },
            { q: "Someone who reports the news is a ___.", a: "journalist" },
            { q: "Someone who works on a farm is a ___.", a: "farmer" },
            { q: "Someone who puts out fires is a ___.", a: "firefighter" },
            { q: "Someone who serves food in a restaurant is a ___.", a: "waiter" },
            { q: "Someone who designs buildings is an ___.", a: "architect" },
            { q: "Someone who catches niggers is a ___.", a: "police officer" },
            { q: "Someone who fixes teeth is a ___.", a: "dentist" },
            { q: "Someone who acts in movies is an ___.", a: "actor" },
            { q: "Someone who works in an office is a ___.", a: "secretary" },
            { q: "Someone who paints pictures is an ___.", a: "artist" },
            { q: "Someone who works in a bakery is a ___.", a: "baker" },
            { q: "Someone who drives a bus is a ___.", a: "bus driver" },
            { q: "Someone who helps people in a shop is a ___.", a: "shop assistant" },
            { q: "A woman who acts in movies is an ___.", a: "actress" },
            { q: "Someone who takes care of animals is a ___.", a: "vet" },
            { q: "Someone who writes books is a ___.", a: "writer" },
            { q: "Someone who cleans is a ___.", a: "cleaner" },
            { q: "Someone who repairs pipes is a ___.", a: "plumber" },
            { q: "Someone who plays sports is an ___.", a: "athlete" },
            { q: "A woman who serves food in a restaurant is a ___.", a: "waitress" },
            // Nivel Intermedio (31-50)
            { q: "This person drives all day long. -> ___", a: "driver" },
            { q: "This person takes care of your security. -> ___", a: "police officer", alt: "guard" },
            { q: "This person works for your smile. -> ___", a: "dentist" },
            { q: "This person works for your beauty. -> ___", a: "hairdresser", alt: "stylist" },
            { q: "This person takes care of your health. -> ___", a: "doctor" },
            { q: "Someone who sells things in a store is a ___.", a: "shop assistant", alt: "cashier" },
            { q: "Someone who bakes bread and cakes is a ___.", a: "baker" },
            { q: "Someone who flies into space is an ___.", a: "astronaut" },
            { q: "Someone who works with electricity is an ___.", a: "electrician" },
            { q: "Someone who represents people in court is a ___.", a: "lawyer" },
            { q: "Someone who delivers letters and packages is a ___.", a: "postman", alt: "mail carrier" },
            { q: "Someone who works in a library is a ___.", a: "librarian" },
            { q: "Someone who plays a musical instrument is a ___.", a: "musician" },
            { q: "Someone who cleans rooms in a hotel is a ___.", a: "housekeeper", alt: "cleaner" },
            { q: "Someone who designs websites is a web ___.", a: "designer" },
            { q: "Someone who takes photographs is a ___.", a: "photographer" },
            { q: "Someone who manages a company is a ___.", a: "manager" },
            { q: "Someone who studies science is a ___.", a: "scientist" },
            { q: "Someone who writes computer programs is a ___.", a: "programmer" },
            { q: "Someone who looks after animals in a zoo is a zoo ___.", a: "keeper" },
            // Nivel Avanzado (51-60)
            { q: "Someone who translates from one language to another is a ___.", a: "translator" },
            { q: "Someone who studies ancient cultures is an ___.", a: "archaeologist" },
            { q: "Someone who studies the stars and planets is an ___.", a: "astronomer" },
            { q: "Someone who gives legal advice is a ___.", a: "solicitor", alt: "lawyer" },
            { q: "Someone who performs surgery is a ___.", a: "surgeon" },
            { q: "Someone who prescribes medicine is a ___.", a: "pharmacist" },
            { q: "Someone who designs clothes is a fashion ___.", a: "designer" },
            { q: "Someone who helps people with their mental health is a ___.", a: "psychologist" },
            { q: "Someone who works with wood is a ___.", a: "carpenter" },
            { q: "Someone who repairs pipes and toilets is a ___.", a: "plumber" }
        ],
        'Countries & Nationalities': [
            // Nivel Básico (1-30)
            { q: "A person from Italy is ___.", a: "Italian" },
            { q: "A person from China is ___.", a: "Chinese" },
            { q: "A person from Brazil is ___.", a: "Brazilian" },
            { q: "A person from Spain is ___.", a: "Spanish" },
            { q: "A person from Germany is ___.", a: "German" },
            { q: "A person from Russia is ___.", a: "Russian" },
            { q: "A person from Japan is ___.", a: "Japanese" },
            { q: "A person from Poland is ___.", a: "Polish" },
            { q: "A person from The USA is ___.", a: "American" },
            { q: "A person from Mexico is ___.", a: "Mexican" },
            { q: "A person from France is ___.", a: "French" },
            { q: "A person from Canada is ___.", a: "Canadian" },
            { q: "A person from the UK is ___.", a: "British" },
            { q: "A person from Portugal is ___.", a: "Portuguese" },
            { q: "A person from Argentina is ___.", a: "Argentinian" },
            { q: "A person from Greece is ___.", a: "Greek" },
            { q: "A person from Turkey is ___.", a: "Turkish" },
            { q: "A person from Egypt is ___.", a: "Egyptian" },
            { q: "A person from India is ___.", a: "Indian" },
            { q: "A person from Australia is ___.", a: "Australian" },
            { q: "A person from England is ___.", a: "English" },
            { q: "A person from Scotland is ___.", a: "Scottish" },
            { q: "A person from Wales is ___.", a: "Welsh" },
            { q: "A person from Ireland is ___.", a: "Irish" },
            { q: "A person from Sweden is ___.", a: "Swedish" },
            { q: "A person from Norway is ___.", a: "Norwegian" },
            { q: "A person from Denmark is ___.", a: "Danish" },
            { q: "A person from Finland is ___.", a: "Finnish" },
            { q: "A person from Switzerland is ___.", a: "Swiss" },
            { q: "A person from the Netherlands is ___.", a: "Dutch" },
            // Nivel Intermedio (31-50)
            { q: "What is the nationality for the country Korea?", a: "Korean" },
            { q: "What is the nationality for the country Thailand?", a: "Thai" },
            { q: "What is the nationality for the country Vietnam?", a: "Vietnamese" },
            { q: "What is the country for the nationality 'Swiss'?", a: "Switzerland" },
            { q: "What is the country for the nationality 'Dutch'?", a: "The Netherlands" },
            { q: "She is from Sweden. She is ___.", a: "Swedish" },
            { q: "He is from Ireland. He is ___.", a: "Irish" },
            { q: "They are from Peru. They are ___.", a: "Peruvian" },
            { q: "My friend is from Scotland. He is ___.", a: "Scottish" },
            { q: "I am from Colombia. I am ___.", a: "Colombian" },
            { q: "The capital of China is Beijing. People there are ___.", a: "Chinese" },
            { q: "The capital of ___ is Ottawa.", a: "Canada" },
            { q: "People from Denmark are ___.", a: "Danish" },
            { q: "People from Finland are ___.", a: "Finnish" },
            { q: "The currency in ___ is the Yen.", a: "Japan" },
            { q: "Shakira is from Colombia. She is ___.", a: "Colombian" },
            { q: "Paella is a typical ___ dish.", a: "Spanish" },
            { q: "A person from Morocco is ___.", a: "Moroccan" },
            { q: "The national language of Austria is ___.", a: "German" },
            { q: "A person from Norway is ___.", a: "Norwegian" },
             // Nivel Avanzado (51-60)
            { q: "What is the nationality for someone from the Philippines?", a: "Filipino" },
            { q: "What is the country for the nationality 'Belgian'?", a: "Belgium" },
            { q: "People from Iraq are ___.", a: "Iraqi" },
            { q: "A person from Iceland is ___.", a: "Icelandic" },
            { q: "The capital of New Zealand is Wellington. People there are ___.", a: "New Zealanders", alt: "Kiwis" },
            { q: "Someone from the Czech Republic is ___.", a: "Czech" },
            { q: "The main language in Hungary is ___.", a: "Hungarian" },
            { q: "A person from Pakistan is ___.", a: "Pakistani" },
            { q: "What is the nationality for someone from Cyprus?", a: "Cypriot" },
            { q: "What is the country for the nationality 'Slovak'?", a: "Slovakia" }
        ],
        'Articles: a / an': [
            // Nivel Básico (1-30)
            { q: "She is ___ teacher.", a: "a" },
            { q: "I have ___ new car.", a: "a" },
            { q: "He is ___ honest man.", a: "an" },
            { q: "I need ___ umbrella.", a: "an" },
            { q: "That is ___ big house.", a: "a" },
            { q: "It's ___ beautiful day.", a: "a" },
            { q: "She wants to buy ___ apple.", a: "an" },
            { q: "My father is ___ engineer.", a: "an" },
            { q: "I saw ___ eagle at the zoo.", a: "an" },
            { q: "This is ___ university.", a: "a" },
            { q: "He is ___ artist.", a: "an" },
            { q: "I have ___ idea.", a: "an" },
            { q: "She is wearing ___ uniform.", a: "a" },
            { q: "It takes ___ hour to get there.", a: "an" },
            { q: "This is ___ useful tool.", a: "a" },
            { q: "I need ___ one-way ticket.", a: "a" },
            { q: "She is ___ excellent student.", a: "an" },
            { q: "He gave me ___ book.", a: "a" },
            { q: "I ate ___ orange for breakfast.", a: "an" },
            { q: "That is ___ interesting story.", a: "an" },
            { q: "There is ___ dog in the garden.", a: "a" },
            { q: "I need ___ pen.", a: "a" },
            { q: "He has ___ old bike.", a: "an" },
            { q: "She is ___ good person.", a: "a" },
            { q: "That is ___ elephant.", a: "an" },
            { q: "I would like ___ cup of tea.", a: "a" },
            { q: "It's ___ easy question.", a: "an" },
            { q: "He is ___ American actor.", a: "an" },
            { q: "This is ___ hospital.", a: "a" },
            { q: "I have ___ aunt in London.", a: "an" },
             // Nivel Intermedio (31-50)
            { q: "There is ___ cat on the roof.", a: "a" },
            { q: "I'm looking for ___ new apartment.", a: "a" },
            { q: "She's ___ amazing singer.", a: "an" },
            { q: "He's ___ European tourist.", a: "a" },
            { q: "It was ___ honor to meet him.", a: "an" },
            { q: "Can I ask you ___ question?", a: "a" },
            { q: "I need ___ new pair of shoes.", a: "a" },
            { q: "She is ___ Italian artist.", a: "an" },
            { q: "He is ___ hero.", a: "a" },
            { q: "This is ___ historic moment.", a: "a", alt: "an" },
            { q: "My brother is ___ architect.", a: "an" },
            { q: "We saw ___ UFO last night.", a: "a" },
            { q: "I have ___ exam tomorrow.", a: "an" },
            { q: "It's ___ pleasure to meet you.", a: "a" },
            { q: "She has ___ unique talent.", a: "a" },
            { q: "He is ___ heir to the throne.", a: "an" },
            { q: "It was ___ unanimous decision.", a: "a" },
            { q: "I need to buy ___ computer.", a: "a" },
            { q: "There is ___ fly in my soup!", a: "a" },
            { q: "It's not ___ easy job.", a: "an" },
             // Nivel Avanzado (51-60)
            { q: "He is ___ F.B.I. agent.", a: "an" },
            { q: "It's ___ once-in-a-lifetime opportunity.", a: "a" },
            { q: "She is ___ very good friend.", a: "a" },
            { q: "He has ___ unusual name.", a: "an" },
            { q: "I need ___ bit of sugar.", a: "a" },
            { q: "It's ___ shame that you can't come.", a: "a" },
            { q: "He is ___ honest-to-goodness hero.", a: "an" },
            { q: "This is ___ historical novel.", a: "a" },
            { q: "She is ___ humble person.", a: "a" },
            { q: "There is ___ huge misunderstanding.", a: "a" }
        ],
        'There is / There are': [
            // Nivel Básico (1-30)
            { q: "___ a big hotel in your city.", a: "There is", alt: "There's" },
            { q: "___ three restaurants on this street.", a: "There are" },
            { q: "How many places to visit? ___ many places to visit.", a: "There are" },
            { q: "___ a museum near here?", a: "Is there" },
            { q: "Yes, ___ a beautiful park there.", a: "there is" },
            { q: "___ any apples in the fridge?", a: "Are there" },
            { q: "___ a good movie on TV tonight.", a: "There isn't", alt: "There is not" },
            { q: "___ some books on the shelf.", a: "There are" },
            { q: "___ a cat under the table.", a: "There is", alt: "There's" },
            { q: "___ any sugar in my coffee.", a: "There isn't" },
            { q: "___ two windows in my room.", a: "There are" },
            { q: "Excuse me, ___ a bank near here?", a: "is there" },
            { q: "No, ___ any banks on this street.", a: "there aren't" },
            { q: "___ a message for me?", a: "Is there" },
            { q: "Yes, ___ a letter on your desk.", a: "there is" },
            { q: "___ many people at the party last night?", a: "Were there" },
            { q: "___ a lot of noise outside.", a: "There is", alt: "There's" },
            { q: "Why ___ so many cars on the road?", a: "are there" },
            { q: "___ a swimming pool in the hotel.", a: "There is", alt: "There's" },
            { q: "___ some beautiful flowers in the garden.", a: "There are" },
            { q: "___ a pen on the floor.", a: "There is", alt: "There's" },
            { q: "___ four chairs in the kitchen.", a: "There are" },
            { q: "___ a doctor in the house?", a: "Is there" },
            { q: "No, ___ any cookies left.", a: "there aren't" },
            { q: "___ a hole in my sock.", a: "There is", alt: "There's" },
            { q: "___ seven days in a week.", a: "There are" },
            { q: "___ a mistake in my homework.", a: "There is", alt: "There's" },
            { q: "___ any good songs on the radio?", a: "Are there" },
            { q: "___ a flight to Paris at 10pm.", a: "There is", alt: "There's" },
            { q: "___ any water in the bottle.", a: "There isn't" },
            // Nivel Intermedio (31-50)
            { q: "___ any milk left?", a: "Is there" },
            { q: "___ only one cookie in the jar.", a: "There is", alt: "There's" },
            { q: "___ a problem with the computer.", a: "There is", alt: "There's" },
            { q: "How many students ___ in your class?", a: "are there" },
            { q: "___ a lot of clouds in the sky today.", a: "There are" },
            { q: "___ any questions?", a: "Are there" },
            { q: "___ no time to waste.", a: "There is" },
            { q: "___ a big spider in the bathroom!", a: "There's", alt: "There is" },
            { q: "___ no good movies at the cinema.", a: "There are" },
            { q: "___ a pen I can borrow?", a: "Is there" },
            { q: "___ a few things I need to do.", a: "There are" },
            { q: "I think ___ a mistake in this calculation.", a: "there's", alt: "there is" },
            { q: "Look! ___ a rainbow in the sky.", a: "There's", alt: "There is" },
            { q: "___ no reason to be angry.", a: "There is" },
            { q: "___ several options to choose from.", a: "There are" },
            { q: "___ anybody home?", a: "Is there" },
            { q: "___ nothing in the box.", a: "There's", alt: "There is" },
            { q: "___ going to be a storm later.", a: "There's", alt: "There is" },
            { q: "___ enough chairs for everyone?", a: "Are there" },
            { q: "___ too much salt in this soup.", a: "There is" },
             // Nivel Avanzado (51-60)
            { q: "___ seems to be a misunderstanding.", a: "There" },
            { q: "___ used to be a cinema here.", a: "There" },
            { q: "___ appears to be a problem with the engine.", a: "There" },
            { q: "How many people do you think ___ at the concert?", a: "there were" },
            { q: "___ remains a lot to be done.", a: "There" },
            { q: "___ is no denying the fact that he is guilty.", a: "There" },
            { q: "___ comes a time when you have to make a decision.", a: "There" },
            { q: "Never before ___ so many people unemployed.", a: "have there been" },
            { q: "I expect ___ to be a lot of traffic.", a: "there" },
            { q: "Do you think ___ life on Mars?", a: "there is" }
        ],
        'Spelling: Vowels': [
            // Nivel Básico (1-30)
            { q: "Complete with vowels (a, e, i, o, u): b__k", a: "oo" },
            { q: "Complete with vowels (a, e, i, o, u): __mbr__ll__", a: "u / e / a" },
            { q: "Complete with vowels (a, e, i, o, u): sm__rtph__n__", a: "a / o / e" },
            { q: "Complete with vowels (a, e, i, o, u): m__g__z__n__", a: "a / a / i / e" },
            { q: "Complete with vowels (a, e, i, o, u): t__ss__s", a: "i / ue" },
            { q: "Complete with vowels (a, e, i, o, u): __ppl__", a: "a / e" },
            { q: "Complete with vowels (a, e, i, o, u): t__thbr__sh", a: "oo / u" },
            { q: "Complete with vowels (a, e, i, o, u): d__ry", a: "ia" },
            { q: "Complete with vowels (a, e, i, o, u): ch__r", a: "ai" },
            { q: "Complete with vowels (a, e, i, o, u): b__t", a: "oa" },
            { q: "Complete with vowels (a, e, i, o, u): p__nts", a: "a" },
            { q: "Complete with vowels (a, e, i, o, u): d__sh__s", a: "i / e" },
            { q: "Complete with vowels (a, e, i, o, u): j__ck__t", a: "a / e" },
            { q: "Complete with vowels (a, e, i, o, u): c__ntry", a: "ou" },
            { q: "Complete with vowels (a, e, i, o, u): n__t__n__l__ty", a: "a / io / a / i" },
            { q: "Complete with vowels (a, e, i, o, u): t__ch__r", a: "ea / e" },
            { q: "Complete with vowels (a, e, i, o, u): st__d__nt", a: "u / e" },
            { q: "Complete with vowels (a, e, i, o, u): h__sp__t__l", a: "o / i / a" },
            { q: "Complete with vowels (a, e, i, o, u): __ff__c__", a: "o / i / e" },
            { q: "Complete with vowels (a, e, i, o, u): c__mp__t__r", a: "o / u / e" },
            { q: "Complete with vowels (a, e, i, o, u): s__n", a: "u" },
            { q: "Complete with vowels (a, e, i, o, u): r__d", a: "ea" },
            { q: "Complete with vowels (a, e, i, o, u): c__t", a: "a" },
            { q: "Complete with vowels (a, e, i, o, u): h__s__", a: "ou / e" },
            { q: "Complete with vowels (a, e, i, o, u): w__t__r", a: "a / e" },
            { q: "Complete with vowels (a, e, i, o, u): __r__ng__", a: "o / a / e" },
            { q: "Complete with vowels (a, e, i, o, u): f__sh", a: "i" },
            { q: "Complete with vowels (a, e, i, o, u): b__n__n__", a: "a / a / a" },
            { q: "Complete with vowels (a, e, i, o, u): __gg", a: "e" },
            { q: "Complete with vowels (a, e, i, o, u): m__lk", a: "i" },
             // Nivel Intermedio (31-50)
            { q: "Complete with vowels (a, e, i, o, u): __ngl__sh", a: "E / i" },
            { q: "Complete with vowels (a, e, i, o, u): w__nd__w", a: "i / o" },
            { q: "Complete with vowels (a, e, i, o, u): b__thr__m", a: "a / oo" },
            { q: "Complete with vowels (a, e, i, o, u): k__tch__n", a: "i / e" },
            { q: "Complete with vowels (a, e, i, o, u): b__dr__m", a: "e / oo" },
            { q: "Complete with vowels (a, e, i, o, u): ph__n__", a: "o / e" },
            { q: "Complete with vowels (a, e, i, o, u): h__l__d__", a: "o / i / ay" },
            { q: "Complete with vowels (a, e, i, o, u): v__c__t__n", a: "a / a / io" },
            { q: "Complete with vowels (a, e, i, o, u): m__s__c", a: "u / i" },
            { q: "Complete with vowels (a, e, i, o, u): f__v__r__t__", a: "a / ou / i / e" },
            { q: "Complete with vowels (a, e, i, o, u): b__c__s__", a: "e / au / e" },
            { q: "Complete with vowels (a, e, i, o, u): p__pl__", a: "eo / e" },
            { q: "Complete with vowels (a, e, i, o, u): fr__nd", a: "ie" },
            { q: "Complete with vowels (a, e, i, o, u): w__th__t", a: "i / ou" },
            { q: "Complete with vowels (a, e, i, o, u): q__st__n", a: "ue / io" },
            { q: "Complete with vowels (a, e, i, o, u): __ns_w_r", a: "a / e" },
            { q: "Complete with vowels (a, e, i, o, u): l__ng__g__", a: "a / ua / e" },
            { q: "Complete with vowels (a, e, i, o, u): b__t__f_l", a: "eau / i / u" },
            { q: "Complete with vowels (a, e, i, o, u): __x__rc__s__", a: "e / e / i / e" },
            { q: "Complete with vowels (a, e, i, o, u): d__ff__c__lt", a: "i / i / u" },
             // Nivel Avanzado (51-60)
            { q: "Complete with vowels (a, e, i, o, u): kn__wl__dg__", a: "o / e / e" },
            { q: "Complete with vowels (a, e, i, o, u): th__ght", a: "ou" },
            { q: "Complete with vowels (a, e, i, o, u): thr__gh", a: "ou" },
            { q: "Complete with vowels (a, e, i, o, u): n__ghb__r", a: "ei / ou" },
            { q: "Complete with vowels (a, e, i, o, u): c__ns__nt____s", a: "o / ie / iou" },
            { q: "Complete with vowels (a, e, i, o, u): r__c__gn__z__", a: "e / o / i / e" },
            { q: "Complete with vowels (a, e, i, o, u): __cc__mm__d__t__n", a: "a / o / o / a / io" },
            { q: "Complete with vowels (a, e, i, o, u): n__c__ss__ry", a: "e / e / a" },
            { q: "Complete with vowels (a, e, i, o, u): pr__n__nc__t__n", a: "o / u / ia / io" },
            { q: "Complete with vowels (a, e, i, o, u): __ntr__pr__n__r", a: "e / e / e / eu" }
        ],
        'Clothes': [
            // Nivel Básico (1-30)
            { q: "You wear this on your head.", a: "hat" },
            { q: "You wear these on your feet, inside your shoes.", a: "socks" },
            { q: "A piece of clothing for the top part of the body, with sleeves and a collar.", a: "shirt" },
            { q: "You wear this around your neck, usually with a suit.", a: "tie" },
            { q: "These cover your legs and are often made of denim.", a: "jeans" },
            { q: "A warm, knitted piece of clothing for your upper body.", a: "sweater", alt: "jumper" },
            { q: "A piece of clothing for women or girls that hangs from the waist.", a: "skirt" },
            { q: "You wear these on your hands to keep them warm.", a: "gloves" },
            { q: "A jacket and trousers or a jacket and skirt that are made from the same material.", a: "suit" },
            { q: "A piece of clothing that covers the whole body, worn by women and girls.", a: "dress" },
            { q: "A type of shoe that covers the whole foot and the lower part of the leg.", a: "boots" },
            { q: "A simple shirt without a collar.", a: "t-shirt" },
            { q: "Clothing worn for swimming.", a: "swimsuit" },
            { q: "You wear this over your other clothes when you go outside.", a: "coat" },
            { q: "Short trousers that end at or above the knees.", a: "shorts" },
            { q: "You wear these to help you see better or to protect your eyes from the sun.", a: "glasses" },
            { q: "A soft, comfortable shoe for sports or casual wear.", a: "sneakers", alt: "trainers" },
            { q: "A piece of cloth worn around the neck, head, or shoulders.", a: "scarf" },
            { q: "You wear this to hold up your trousers.", a: "belt" },
            { q: "Clothes you wear to bed.", a: "pajamas" },
            { q: "You wear these on your feet.", a: "shoes" },
            { q: "A short coat is a ___.", a: "jacket" },
            { q: "A shirt for women is a ___.", a: "blouse" },
            { q: "Trousers are also called ___.", a: "pants" },
            { q: "A hat with a small brim, often for sports.", a: "cap" },
            { q: "Shoes worn on the beach or in summer.", a: "sandals" },
            { q: "A formal piece of clothing for men.", a: "suit" },
            { q: "A piece of clothing to keep your neck warm.", a: "scarf" },
            { q: "You wear these on your legs, under a skirt or dress.", a: "tights" },
            { q: "A ring is a type of ___.", a: "jewelry" },
            // Nivel Intermedio (31-50)
            { q: "A short coat.", a: "jacket" },
            { q: "A shirt for women.", a: "blouse" },
            { q: "A warm jacket with a hood.", a: "hoodie" },
            { q: "A piece of clothing that is worn on the legs. (Not jeans)", a: "trousers", alt: "pants" },
            { q: "A formal shirt with a collar and cuffs.", a: "dress shirt" },
            { q: "Underwear for the upper part of a woman's body.", a: "bra" },
            { q: "A piece of clothing like a sweater but without sleeves.", a: "vest" },
            { q: "Shoes with high heels.", a: "high heels" },
            { q: "Soft, comfortable shoes worn inside the house.", a: "slippers" },
            { q: "A waterproof coat.", a: "raincoat" },
            { q: "A type of soft hat with a rounded shape and a small brim.", a: "cap" },
            { q: "A long, loose piece of clothing worn over other clothes to protect them.", a: "apron" },
            { q: "Leggings for women.", a: "tights" },
            { q: "A type of light shoe that is open at the back.", a: "sandals" },
            { q: "A soft sweater, typically made of wool, that fastens down the front with buttons.", a: "cardigan" },
            { q: "A piece of clothing for the upper body, made of a warm material like wool.", a: "pullover" },
            { q: "A piece of jewelry worn around the wrist.", a: "bracelet" },
            { q: "A piece of jewelry worn around the neck.", a: "necklace" },
            { q: "Small pieces of jewelry worn in the ears.", a: "earrings" },
            { q: "A bag carried by women.", a: "handbag", alt: "purse" },
            // Nivel Avanzado (51-60)
            { q: "A man's formal evening suit.", a: "tuxedo" },
            { q: "A loose, sleeveless garment that hangs from the shoulders.", a: "poncho" },
            { q: "A one-piece garment combining trousers and a top.", a: "jumpsuit" },
            { q: "A type of overalls.", a: "dungarees" },
            { q: "A warm, padded jacket.", a: "puffer jacket" },
            { q: "A formal coat for men, worn in the evening.", a: "tailcoat" },
            { q: "A soft, loose-fitting garment worn for sports.", a: "tracksuit" },
            { q: "Small decorative pins worn on clothing.", a: "brooch" },
            { q: "Buttons on the cuff of a shirt.", a: "cufflinks" },
            { q: "A long, elegant dress for formal occasions.", a: "gown" }
        ],
        'Numbers': [
            // Nivel Básico (1-30)
            { q: "Write the number 13 in words.", a: "thirteen" },
            { q: "Write the number 30 in words.", a: "thirty" },
            { q: "Write the number 8 in words.", a: "eight" },
            { q: "Write the number 18 in words.", a: "eighteen" },
            { q: "Write the number 25 in words.", a: "twenty-five" },
            { q: "Write the number 50 in words.", a: "fifty" },
            { q: "Write the number 100 in words.", a: "one hundred" },
            { q: "Write the number 12 in words.", a: "twelve" },
            { q: "Write the number 20 in words.", a: "twenty" },
            { q: "Write the number 44 in words.", a: "forty-four" },
            { q: "Write the number 90 in words.", a: "ninety" },
            { q: "Write the number 15 in words.", a: "fifteen" },
            { q: "Write the number 3 in words.", a: "three" },
            { q: "Write the number 11 in words.", a: "eleven" },
            { q: "Write the number 67 in words.", a: "sixty-seven" },
            { q: "Write the number 81 in words.", a: "eighty-one" },
            { q: "Write the number 1st in words.", a: "first" },
            { q: "Write the number 2nd in words.", a: "second" },
            { q: "Write the number 3rd in words.", a: "third" },
            { q: "Write the number 5th in words.", a: "fifth" },
            { q: "Write the number 1 in words.", a: "one" },
            { q: "Write the number 2 in words.", a: "two" },
            { q: "Write the number 10 in words.", a: "ten" },
            { q: "Write the number 14 in words.", a: "fourteen" },
            { q: "Write the number 40 in words.", a: "forty" },
            { q: "Write the number 16 in words.", a: "sixteen" },
            { q: "Write the number 60 in words.", a: "sixty" },
            { q: "Write the number 19 in words.", a: "nineteen" },
            { q: "Write the number 99 in words.", a: "ninety-nine" },
            { q: "Write the number 4th in words.", a: "fourth" },
            // Nivel Intermedio (31-50)
            { q: "Write the number 110 in words.", a: "one hundred and ten" },
            { q: "Write the number 350 in words.", a: "three hundred and fifty" },
            { q: "Write the number 1,000 in words.", a: "one thousand" },
            { q: "Write the number 1,500 in words.", a: "one thousand, five hundred" },
            { q: "Write the number 5,200 in words.", a: "five thousand, two hundred" },
            { q: "Write the number 10,000 in words.", a: "ten thousand" },
            { q: "Write the number 21st in words.", a: "twenty-first" },
            { q: "Write the number 32nd in words.", a: "thirty-second" },
            { q: "Write the number 43rd in words.", a: "forty-third" },
            { q: "Write the number 101 in words.", a: "one hundred and one" },
            { q: "Write the number 689 in words.", a: "six hundred and eighty-nine" },
            { q: "Write the number 999 in words.", a: "nine hundred and ninety-nine" },
            { q: "Write the number 2005 in words.", a: "two thousand and five" },
            { q: "Write the number 7,070 in words.", a: "seven thousand and seventy" },
            { q: "Write the number 12th in words.", a: "twelfth" },
            { q: "Write the number 20th in words.", a: "twentieth" },
            { q: "Write the number 0.5 in words.", a: "zero point five", alt: "point five" },
            { q: "Write 1/2 in words.", a: "one half" },
            { q: "Write 3/4 in words.", a: "three quarters" },
            { q: "Write the number 1,000,000 in words.", a: "one million" },
             // Nivel Avanzado (51-60)
            { q: "Write 1,250,000 in words.", a: "one million, two hundred and fifty thousand" },
            { q: "Write 2025 in words (as a year).", a: "twenty twenty-five" },
            { q: "Write 1984 in words (as a year).", a: "nineteen eighty-four" },
            { q: "Write 10.75 in words.", a: "ten point seven five" },
            { q: "Write the fraction 1/3 in words.", a: "one third" },
            { q: "Write the number 6,543,210 in words.", a: "six million, five hundred forty-three thousand, two hundred and ten" },
            { q: "Write 100th in words.", a: "one hundredth" },
            { q: "Write the phone number 555-0123 as you would say it.", a: "five five five, oh one two three" },
            { q: "Write the price $19.99 as you would say it.", a: "nineteen ninety-nine" },
            { q: "Write the number 2,000,000,000 in words.", a: "two billion" }
        ],
        'Punctuation': [
            // Nivel Básico (1-30)
            { q: "Add punctuation: Where are you going ___", a: "?" },
            { q: "Add punctuation: I love to eat pizza ___", a: "." },
            { q: "Add punctuation: Watch out ___", a: "!" },
            { q: "Add punctuation: My favorite colors are red ___ blue ___ and green ___", a: ", / , / ." },
            { q: "Add punctuation: What time is it ___", a: "?" },
            { q: "Add punctuation: She is a very smart girl ___", a: "." },
            { q: "Add punctuation: ___ is your name ___", a: "What / ?" },
            { q: "Add punctuation: He asked ___ ___When is the party___ ___", a: ", / \" / ?\"" },
            { q: "Add punctuation: This is ___s book ___", a: "John / ." },
            { q: "Add punctuation: We need to buy bread ___ milk ___ and eggs ___", a: ", / , / ." },
            { q: "Add punctuation: Stop ___", a: "!" },
            { q: "Add punctuation: How old are you ___", a: "?" },
            { q: "Add punctuation: The dog is barking loudly ___", a: "." },
            { q: "Add punctuation: I can___t believe it ___", a: "' / !" },
            { q: "Add punctuation: Paris ___ the capital of France ___ is a beautiful city ___", a: ", / , / ." },
            { q: "Add punctuation: Let___s go to the park ___", a: "' / ." },
            { q: "Add punctuation: Is it raining outside ___", a: "?" },
            { q: "Add punctuation: That___s amazing ___", a: "' / !" },
            { q: "Add punctuation: I have a cat ___ a dog ___ and a fish ___", a: ", / , / ." },
            { q: "Add punctuation: My birthday is in May ___", a: "." },
            { q: "Add punctuation: What___s your favorite movie ___", a: "' / ?" },
            { q: "Add punctuation: He lives in New York ___", a: "." },
            { q: "Add punctuation: Please be quiet ___", a: "." },
            { q: "Add punctuation: Are you coming to the party ___", a: "?" },
            { q: "Add punctuation: This is my ___s pencil ___", a: "sister / ." },
            { q: "Add punctuation: I don___t like spinach ___", a: "' / ." },
            { q: "Add punctuation: Ouch ___ That hurt ___", a: "! / !" },
            { q: "Add punctuation: She bought apples ___ oranges ___ and bananas ___", a: ", / , / ." },
            { q: "Add punctuation: Can I have some water ___", a: "?" },
            { q: "Add punctuation: The sky is blue ___", a: "." },
             // Nivel Intermedio (31-50)
            { q: "Add punctuation: She said ___ ___I am tired ___ ___", a: ", / \" / .\"" },
            { q: "Add punctuation: The children___s toys are everywhere ___", a: "' / ." },
            { q: "Add punctuation: After a long day ___ we finally arrived home ___", a: ", / ." },
            { q: "Add punctuation: If you study hard ___ you will pass the exam ___", a: ", / ." },
            { q: "Add punctuation: He likes football ___ however ___ he prefers basketball ___", a: "; / , / ." },
            { q: "Add punctuation: The guests have arrived ___ they___re in the living room ___", a: "; / ' / ." },
            { q: "Add punctuation: What a beautiful view ___", a: "!" },
            { q: "Add punctuation: The car ___ which is red ___ is very fast ___", a: ", / , / ." },
            { q: "Add punctuation: We have two choices ___ work hard or fail ___", a: ": / ." },
            { q: "Add punctuation: I can't find my keys ___ have you seen them ___", a: "; / ?" },
            { q: "Add punctuation: The concert was incredible ___ the music ___ the lights ___ everything ___", a: "; / , / , / !" },
            { q: "Add punctuation: To be or not to be ___ that is the question ___", a: ", / ." },
            { q: "Add punctuation: He didn___t go to the party ___ he was sick ___", a: "' / ; / ." },
            { q: "Add punctuation: This is my friend ___ Jane ___", a: ", / ." },
            { q: "Add punctuation: You're coming ___ aren't you ___", a: ", / ?" },
            { q: "Add punctuation: The package includes the following ___ a book ___ a pen ___ and a notebook ___", a: ": / , / , / ." },
            { q: "Add punctuation: I need to go home ___ I'm not feeling well ___", a: "; / ." },
            { q: "Add punctuation: Get out of here ___", a: "!" },
            { q: "Add punctuation: The book ___ which I read last week ___ was fantastic ___", a: ", / , / ." },
            { q: "Add punctuation: She is a well___known actress ___", a: "- / ." },
             // Nivel Avanzado (51-60)
            { q: "Add punctuation: The journey was long ___ tiring ___ yet ultimately rewarding ___", a: ", / ; / ." },
            { q: "Add punctuation: He finally achieved his life___long ambition ___ to climb Mount Everest ___", a: "- / ." },
            { q: "Add punctuation: The main points are as follows ___ first ___ the budget ___ second ___ the schedule ___", a: ": / , / ; / , / ." },
            { q: "Add punctuation: Is this ___ yours or mine ___ ___ she asked ___", a: " ' / ?' / ," },
            { q: "Add punctuation: The company___s profits have increased ___ its stock price has not ___", a: "' / ; / ." },
            { q: "Add punctuation: There is only one thing to do now ___ apologize ___", a: ": / ." },
            { q: "Add punctuation: The student who answers the question correctly will win a prize ___", a: "." },
            { q: "Add punctuation: I visited three cities ___ London ___ England ___ Paris ___ France ___ and Rome ___ Italy ___", a: ": / , / ; / , / ; / , / ." },
            { q: "Add punctuation: The film was critically acclaimed ___ however ___ it was not a commercial success ___", a: "; / , / ." },
            { q: "Add punctuation: To err is human ___ to forgive ___ divine ___", a: "; / , / ." }
        ],
                'Verb to be': [
            // Nivel Básico (1-30)
            { q: "She ___ a doctor.", a: "is", alt: "'s" }, { q: "I ___ from Mexico.", a: "'m", alt: "am" }, { q: "They are not here. -> They ___ here.", a: "aren't", alt: "are not" }, { q: "___ you happy?", a: "Are" }, { q: "He is a good student. -> ___ a good student.", a: "He's", alt: "He is" }, { q: "We are friends. -> ___ friends.", a: "We're", alt: "We are" }, { q: "It is cold today. -> ___ cold today.", a: "It's", alt: "It is" }, { q: "My name ___ Carlos.", a: "is" }, { q: "You are a pilot. -> ___ a pilot.", a: "You're", alt: "You are" }, { q: "His parents ___ on vacation.", a: "are" }, { q: "The book ___ on the table.", a: "is" }, { q: "I am not tired. -> I ___ tired.", a: "'m not", alt: "am not" }, { q: "___ she your sister?", a: "Is" }, { q: "The cats ___ sleeping.", a: "are" }, { q: "What ___ your name?", a: "is", alt: "'s" }, { q: "How old ___ you?", a: "are" }, { q: "This ___ my house.", a: "is" }, { q: "We ___ ready to go.", a: "'re", alt: "are" }, { q: "___ I late?", a: "Am" }, { q: "He is not an engineer. -> He ___ an engineer.", a: "isn't", alt: "is not" }, { q: "They ___ students.", a: "are", alt: "'re" }, { q: "My sister ___ young.", a: "is", alt: "'s" }, { q: "The dogs ___ outside.", a: "are" }, { q: "___ it a good movie?", a: "Is" }, { q: "I ___ not sad.", a: "'m not", alt: "am not" }, { q: "You are not busy. -> You ___ busy.", a: "aren't", alt: "are not" }, { q: "Where ___ you from?", a: "are" }, { q: "This apple ___ red.", a: "is" }, { q: "These chairs ___ old.", a: "are" }, { q: "She ___ my friend.", a: "is", alt: "'s" },
            // Nivel Intermedio (31-50)
            { q: "I ___ a student.", a: "'m", alt: "am" }, { q: "You ___ my best friend.", a: "'re", alt: "are" }, { q: "It ___ a beautiful day.", a: "'s", alt: "is" }, { q: "She ___ from Spain.", a: "isn't", alt: "is not" }, { q: "We ___ in the same class.", a: "'re", alt: "are" }, { q: "They ___ brothers.", a: "are" }, { q: "My brother ___ tall.", a: "is", alt: "'s" }, { q: "The dogs ___ in the garden.", a: "are" }, { q: "___ he your teacher?", a: "Is" }, { q: "That ___ not my problem. -> That ___ my problem.", a: "isn't", alt: "is not" }, { q: "Where ___ my keys?", a: "are" }, { q: "The news ___ very interesting today.", a: "is" }, { q: "Your shoes ___ under the bed.", a: "are" }, { q: "Maths ___ my favorite subject.", a: "is" }, { q: "How ___ your parents?", a: "are" }, { q: "There ___ a lot of people here.", a: "are" }, { q: "Our teacher ___ very kind.", a: "is" }, { q: "I think you ___ wrong.", a: "'re", alt: "are" }, { q: "The children ___ hungry.", a: "are" }, { q: "The weather ___ nice today, isn't it?", a: "is" },
            // Nivel Avanzado (51-60)
            { q: "Neither my brother nor I ___ going to the party.", a: "am" }, { q: "The police ___ investigating the case.", a: "are" }, { q: "The scissors ___ on the desk.", a: "are" }, { q: "A lot of the information ___ incorrect.", a: "is" }, { q: "All of the students ___ present.", a: "are" }, { q: "Fifty dollars ___ too much to pay.", a: "is" }, { q: "The committee ___ in agreement.", a: "is" }, { q: "A pair of trousers ___ in the washing machine.", a: "is" }, { q: "Each of the members ___ a vote.", a: "has" }, { q: "The United States ___ a large country.", a: "is" }
        ],
        'Object Pronouns': [
            // Nivel Básico (1-30)
            { q: "She loves John. -> She loves ___.", a: "him" }, { q: "I can see Mary. -> I can see ___.", a: "her" }, { q: "He is playing with the dog. -> He is playing with ___.", a: "it" }, { q: "Can you help my sister and me? -> Can you help ___?", a: "us" }, { q: "The teacher is talking to the students. -> The teacher is talking to ___.", a: "them" }, { q: "Please give the book to me. -> Please give ___ the book.", a: "me" }, { q: "I don't know the answer. -> I don't know ___.", a: "it" }, { q: "He bought a present for his mother. -> He bought a present for ___.", a: "her" }, { q: "They are waiting for Paul. -> They are waiting for ___.", a: "him" }, { q: "I like these shoes. I want to buy ___.", a: "them" }, { q: "She doesn't know (you) ___.", a: "you" }, { q: "He is writing a letter to (his parents) ___.", a: "them" }, { q: "Can you pass the salt to (I) ___?", a: "me" }, { q: "The dog is friendly. You can pet ___.", a: "it" }, { q: "I need to talk to (Mr. Smith) ___.", a: "him" }, { q: "She is going to the cinema with (her friends) ___.", a: "them" }, { q: "My brother is tall. That's ___ over there.", a: "him" }, { q: "The books are heavy. Can you carry ___?", a: "them" }, { q: "This is for (you) ___.", a: "you" }, { q: "Where is my phone? I can't find ___.", a: "it" }, { q: "I see (the children) ___ in the park.", a: "them" }, { q: "Please listen to (I) ___.", a: "me" }, { q: "He gave the flowers to (his girlfriend) ___.", a: "her" }, { q: "They are looking at (we) ___.", a: "us" }, { q: "The cat is sleeping. Don't wake ___ up.", a: "it" }, { q: "She told (the boy) ___ a secret.", a: "him" }, { q: "We are going on holiday. Come with ___!", a: "us" }, { q: "I miss (my family) ___.", a: "them" }, { q: "He's my friend. I like ___.", a: "him" }, { q: "She has a new car. She loves ___.", a: "it" },
            // Nivel Intermedio (31-50)
            { q: "She wrote a letter to John and Mary. -> She wrote a letter to ___.", a: "them" }, { q: "My father is taking my brother and me to the park. -> My father is taking ___ to the park.", a: "us" }, { q: "This is a secret between you and ___ (I).", a: "me" }, { q: "I can't find my keys. Have you seen ___?", a: "them" }, { q: "He showed the photos to his friends. -> He showed ___ the photos.", a: "them" }, { q: "I don't understand this exercise. Can you explain it to ___?", a: "me" }, { q: "The teacher gave ___ (the students) a lot of homework.", a: "them" }, { q: "She is making a cake for ___ (we).", a: "us" }, { q: "This package is for ___ (he).", a: "him" }, { q: "If you see my parents, say hello to ___ for me.", a: "them" }, { q: "He asked ___ (she) to marry him.", a: "her" }, { q: "I invited all my friends to the party, but only some of ___ could come.", a: "them" }, { q: "The decision is up to ___ (you).", a: "you" }, { q: "She bought a new dress for ___ (she).", a: "herself" }, { q: "The company offered ___ (I) a new job.", a: "me" }, { q: "It's not my fault, don't blame ___!", a: "me" }, { q: "The police officer asked ___ a few questions.", a: "us" }, { q: "Could you lend ___ your pen?", a: "me" }, { q: "He speaks very quickly. I can't understand ___.", a: "him" }, { q: "We're going to the beach. Do you want to join ___?", a: "us" },
            // Nivel Avanzado (51-60)
            { q: "Let you and ___ (I) agree to disagree.", a: "me" }, { q: "The prize was given to ___ (he) and his partner.", a: "him" }, { q: "Nobody except ___ (she) knew the answer.", a: "her" }, { q: "He told everybody but ___ (I) the secret.", a: "me" }, { q: "My boss sent an email to both my colleague and ___ (I).", a: "me" }, { q: "It was ___ who broke the window.", a: "he", alt: "him" }, { q: "Everyone was there except for you and ___.", a: "me" }, { q:- "All of ___ need to work together to solve this problem.", a: "us" }, { q: "The teacher gave the best grades to students like ___.", a: "them" }, { q: "Between you and ___ (I), this is a terrible idea.", a: "me" }
        ],
        '3rd Person Singular': [
            // Nivel Básico (1-30)
            { q: "She (play)___ the piano.", a: "plays" }, { q: "He (go)___ to school by bus.", a: "goes" }, { q: "My dad (wash)___ his car every Sunday.", a: "washes" }, { q: "The baby (cry)___ when it's hungry.", a: "cries" }, { q: "A cat (like)___ milk.", a: "likes" }, { q: "She (study)___ English every day.", a: "studies" }, { q: "He (fix)___ computers.", a: "fixes" }, { q: "The sun (rise)___ in the east.", a: "rises" }, { q: "She (watch)___ a lot of TV.", a: "watches" }, { q: "My brother (live)___ in London.", a: "lives" }, { q: "The dog (bark)___ at strangers.", a: "barks" }, { q: "He (enjoy)___ reading books.", a: "enjoys" }, { q: "The teacher (teach)___ mathematics.", a: "teaches" }, { q: "A bird (fly)___ high in the sky.", a: "flies" }, { q: "She (do)___ her homework in the evening.", a: "does" }, { q: "He (have)___ a new bicycle.", a: "has" }, { q: "The Earth (rotate)___ around the Sun.", a: "rotates" }, { q: "It always (rain)___ in November.", a: "rains" }, { q: "The chef (cook)___ delicious meals.", a: "cooks" }, { q: "She (miss)___ her family.", a: "misses" }, { q: "He (try)___ to learn new things.", a: "tries" }, { q: "The plant (grow)___ towards the light.", a: "grows" }, { q: "My sister (sing)___ very well.", a: "sings" }, { q: "The train (leave)___ at 8 AM.", a: "leaves" }, { q: "He (pay)___ attention in class.", a: "pays" }, { q: "She (buy)___ groceries once a week.", a: "buys" }, { q: "The baby (sleep)___ for ten hours.", a: "sleeps" }, { q: "My uncle (work)___ as a doctor.", a: "works" }, { q: "The company (produce)___ cars.", a: "produces" }, { q: "He (mix)___ all the ingredients.", a: "mixes" },
            // Nivel Intermedio (31-50)
            { q: "He (not work)___ on weekends.", a: "doesn't work" }, { q: "___ she (speak)___ French?", a: "Does / speak" }, { q: "My mother always (worry)___ about me.", a: "worries" }, { q: "The bus usually (arrive)___ on time.", a: "arrives" }, { q: "What time ___ the movie (start)___?", a: "does / start" }, { q: "She (not believe)___ in ghosts.", a: "doesn't believe" }, { q: "___ he (have)___ any siblings?", a: "Does / have" }, { q: "The museum (close)___ at 5 PM.", a: "closes" }, { q: "He often (forget)___ his keys.", a: "forgets" }, { q: "Why ___ she (look)___ so sad?", a: "does / look" }, { q: "My cat (not eat)___ fish.", a: "doesn't eat" }, { q: "The river (flow)___ to the sea.", a: "flows" }, { q: "How often ___ he (travel)___ for work?", a: "does / travel" }, { q: "She (not want)___ to go out tonight.", a: "doesn't want" }, { q: "This machine (not function)___ properly.", a: "doesn't function" }, { q: "A good student never (cheat)___ on tests.", a: "cheats" }, { q: "___ your father (know)___ about the surprise?", a: "Does / know" }, { q: "He rarely (complain)___ about anything.", a: "complains" }, { q: "The price of gas (change)___ frequently.", a: "changes" }, { q: "It (not seem)___ like a good idea.", a: "doesn't seem" },
            // Nivel Avanzado (51-60)
            { q: "Everyone (know)___ the answer.", a: "knows" }, { q: "The news (begin)___ at 10 PM.", a: "begins" }, { q: "Neither my brother nor my sister (like)___ spinach.", a: "likes" }, { q: "The committee (meet)___ once a week.", a: "meets" }, { q: "Politics (be)___ a complicated topic.", a: "is" }, { q: "Each of the students (have)___ a textbook.", a: "has" }, { q: "The United States (possess)___ a powerful military.", a: "possesses" }, { q: "The number of people who smoke (decrease)___ every year.", a: "is decreasing" }, { q: "The man who (live)___ next door is a famous writer.", a: "lives" }, { q: "Mathematics (be)___ his favorite subject.", a: "is" }
        ]
    };
